/**
 * CHRONO | Demo UI Logic
 * Handles the dashboard interactivity, Trident gauge updates,
 * and the Protocol-99 agent reasoning simulation.
 */

// --- Demo Data ---
const PRIYA_DEMO = {
    mcf: 0.73,
    signals: {
        wiv: { val: "+0.121", progress: 72, alert: true },
        bav: { val: "+0.096", progress: 45, alert: false },
        icv: { val: "+0.157", progress: 88, alert: true }
    },
    agent_trace: [
        { role: 'thought', content: "MCF score is 0.73. I must first validate the Trident signal to ensure this isn't an artifact of low confidence or transient noise." },
        { role: 'action', content: "validate_trident_signal(wiv_z=2.1, confidence=0.95)" },
        { role: 'observation', content: '{"is_valid": true, "reason": "Signal validated: strong co-movement detected.", "avg_z": 2.1}' },
        { role: 'thought', content: "Signal validated. Now investigating long-term marker trends. I'll query the LDH history to see the trajectory of the Warburg signal." },
        { role: 'action', content: "query_personal_history(marker_name='ldh')" },
        { role: 'observation', content: "LDH trend: increasing. Latest: 214 U/L (from 165 U/L baseline)." },
        { role: 'thought', content: "Sustained LDH elevation detected over 18 months. Now performing a deep-dive into the immune collapse pattern using the Vascular Anomaly Score." },
        { role: 'action', content: "compute_vascular_anomaly_score(nlr=3.12, plr=167.6, rar=3.59)" },
        { role: 'observation', content: '{"vas_score": 6.96, "classification": "CRITICAL"}' },
        { role: 'thought', content: "Vascular Anomaly Score is 6.96 (CRITICAL). Pattern suggests metabolic reprogramming. I will now generate the clinical triage dossier for oncologist review." },
        { role: 'final', content: "Protocol-99 investigation complete. Trident signal validated (Avg Z=2.1). Triage dossier generated and successfully escalated to Oncology Specialist. Case ID: CHRONO-2026-99-A1." }
    ],
    dossier: `
# CHRONO Triage Dossier — Confidential
**Protocol-99 Activation Report**

## Patient Information
- **Patient ID:** priya_demo_001
- **Assessment Date:** 2024-01-18
- **Risk Classification:** CRITICAL

## Investigation Summary
Trident Signal co-movement confirmed. WIV velocity +0.121 units/mo. BAV acceleration +0.096 yrs/mo. ICV deterioration +0.157 units/mo. Personal baseline deviation exceeded 1.5σ for LDH and RDW. VAS score 6.96.

## Clinical Reasoning (Gemma 4 26B)
The Trident Signal co-movement suggests a systemic metabolic shift consistent with pre-cancerous biological states. Specifically, the acceleration of biological age coupled with an increasing Warburg Index indicates aerobic glycolysis dominance, a hallmark of malignant metabolic reprogramming. The immune ratio collapse (NLR > 3.0) confirms inflammatory hijacking.

## Recommendations
1. **Immediate Specialist Review:** Hematology/Oncology consultation recommended.
2. **Supplemental Imaging:** Abdominal/Pelvic ultrasound or PET-CT to evaluate structural correlates.
3. **Tumor Markers:** Baseline CA-125, CA 19-9, and CEA.
4. **Follow-up:** Repeat metabolic panel in 14 days.

---
*Generated by CHRONO Protocol-99 Agent. This is a triage report, not a diagnosis.*
    `
};

// --- DOM Elements ---
const consoleEl = document.getElementById('console');
const viewDossierBtn = document.getElementById('view-dossier-btn');
const dossierModal = document.getElementById('dossier-modal');
const closeModalBtn = document.querySelector('.close-btn');
const dossierContent = document.getElementById('dossier-content');

// --- Functions ---

/**
 * Simulates the agent reasoning process line by line
 */
async function simulateAgent() {
    consoleEl.innerHTML = '';
    
    for (const step of PRIYA_DEMO.agent_trace) {
        const div = document.createElement('div');
        div.className = `step-${step.role}`;
        
        let prefix = '';
        if (step.role === 'thought') prefix = 'THOUGHT: ';
        if (step.role === 'action') prefix = 'ACTION: ';
        if (step.role === 'observation') prefix = 'OBSERVATION: ';
        if (step.role === 'final') prefix = 'FINAL ANSWER: ';
        
        div.innerHTML = `<strong>${prefix}</strong>${step.content}`;
        consoleEl.appendChild(div);
        
        // Scroll to bottom
        consoleEl.scrollTop = consoleEl.scrollHeight;
        
        // Delay for simulation effect
        await new Promise(resolve => setTimeout(resolve, 1500));
    }
}

/**
 * Converts simple Markdown to HTML for the dossier
 */
function renderMarkdown(md) {
    let html = md
        .replace(/^# (.*$)/gim, '<h1>$1</h1>')
        .replace(/^## (.*$)/gim, '<h2>$1</h2>')
        .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
        .replace(/^[-*] (.*$)/gim, '<li>$1</li>');
        
    // Wrap consecutive li elements in a ul
    html = html.replace(/(<li>.*<\/li>\s*)+/g, match => `<ul>${match}</ul>`);
    return html.replace(/\n/g, '<br>');
}

// --- Event Listeners ---

viewDossierBtn.addEventListener('click', () => {
    dossierContent.innerHTML = renderMarkdown(PRIYA_DEMO.dossier);
    dossierModal.classList.add('active');
});

closeModalBtn.addEventListener('click', () => {
    dossierModal.classList.remove('active');
});

// Close modal on click outside
window.addEventListener('click', (e) => {
    if (e.target === dossierModal) {
        dossierModal.classList.remove('active');
    }
});

// --- Initialization ---

window.addEventListener('DOMContentLoaded', () => {
    // Start agent simulation
    simulateAgent();
    
    // Add subtle hover effects to cards
    document.querySelectorAll('.signal-card').forEach(card => {
        card.addEventListener('mouseenter', () => {
            card.style.borderColor = 'var(--primary)';
        });
        card.addEventListener('mouseleave', () => {
            card.style.borderColor = 'var(--border)';
        });
    });
});
